Setup Cypress with Firebase stuff
mn-pollinators/buzz-about pull request #134
Opened 2020-09-15 10:31 UTC by floogulinc

Closes #101

2020-09-29 18:59 UTC, floogulinc commented
TODO: Document `serviceAccount.json`

2020-09-29 21:34 UTC, floogulinc commented
There are docs for setting up the service account stuff here: https://github.com/mn-pollinators/buzz-about/blob/dev-docs/SETUP.md#setting-up-firebase-for-cypress

To build the app and run the Cypress end-to-end tests, start the Firebase emulators and run:
```
npm run e2e
```

To open Cypress (so you can run the tests interactively), start both the Firebase emulators and the development server and run:
```
npm run cy:open
```

2020-09-30 20:06 UTC, helloworld12321 requested changes
This looks wonderful—thank you, Paul! I've made a few minor notes (really tiny ones), but all in all, I'm really excited about this. Can't wait to start writing tests! :)

2020-09-30 23:05 UTC, floogulinc commented on .github/workflows/cypress.yml
> +name: Cypress Tests
I thought we might do that in a separate PR but I can do it here, the question is whether to use the badge for the GH action or the one from the Cypress dashboard.

2020-09-30 23:06 UTC, floogulinc commented on .github/workflows/cypress.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
The Cypress GitHub action runs `npm install` so we need that for the post-install script.

2020-10-01 01:22 UTC, helloworld12321 commented on .github/workflows/cypress.yml
> +name: Cypress Tests
Ooh, if it's convenient for you, I like the idea of having one from the Cypress dashboard! (That sounds fancy.)

2020-10-01 01:22 UTC, helloworld12321 commented on .github/workflows/cypress.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Gotcha—neat, thanks!

2020-10-01 12:43 UTC, helloworld12321 approved these changes
Thumbs up! :+1: This looks like a really good tool.

2020-10-02 03:00 UTC, kklamberty approved these changes

2020-10-02 19:20 UTC, merged