Inform students of their bee's next active period
mn-pollinators/buzz-about pull request #211
Opened 2021-01-19 07:14 UTC by UtkarshKr007

Closes: #210

2021-01-19 18:49 UTC, floogulinc submitted a review, later dismissed
Just one minor formatting thing but otherwise looks great!

2021-01-19 18:49 UTC, floogulinc commented on src/app/services/student-round.service.ts
> +    ),
```suggestion
    map(([species, time]) =>
      species.active_period.find(interval => time.time < interval[0].time)?.[0] ?? null
    ),
```

2021-01-19 20:54 UTC, floogulinc approved these changes

2021-01-19 21:43 UTC, floogulinc requested changes
Joe, KK, and I discussed some of the phrasing and text stuff and have a suggested change to the phrasing of the part that says their species is not active. I also caught a little issue that I think happened with all the branch merging and stuff that happened.

2021-01-19 21:43 UTC, floogulinc commented on src/app/components/student-round/student-round.component.html
> +          {{(roundService.currentBeeSpecies$ | async).name | sentenceCase}} are currently inactive
```suggestion
          {{(roundService.currentBeeSpecies$ | async).name | sentenceCase}}s are not active right now
```

Joe, KK, and I discussed this phrasing and we want to change it a little bit and pluralize the bee name (they all end in "bee" right now so we should make it "bees").

2021-01-19 21:43 UTC, floogulinc commented on src/app/components/student-round/student-round.component.html
> +          You will next be active in {{nextActivePeriodText}}
```suggestion
          You will next be active {{nextActivePeriodText}}
```

The "in" is included in this string where needed. We don't want it to say "in soon" for example.

2021-01-20 06:45 UTC, floogulinc approved these changes

2021-01-20 15:42 UTC, kklamberty approved these changes
This looks great! Nice work!

2021-01-20 15:42 UTC, merged