Add the ability for teachers to display the field guide for students
mn-pollinators/buzz-about pull request #256
Opened 2021-04-06 20:28 UTC by floogulinc

2021-04-08 18:31 UTC, kklamberty requested changes
I'm having some kind of issue with the field guide not always showing the images when I'm looking at an individual item. I'm not sure why. When I refresh, the image will show up. If I'm looking at an individual item, it's also the case that if the host chooses to stop showing the field guide, I can still see the element I'm looking at.

Is there anything I can do to help someone recreate the issue about not being able to see images?

2021-04-08 21:24 UTC, floogulinc commented
@kklamberty We have fixed the issue of the dialog staying open. We have yet to look at the image loading issue but suspect it may just be an issue with Safari that we may not really be able to fix.

2021-04-08 21:47 UTC, kklamberty approved these changes

2021-04-09 16:40 UTC, audreylemeur approved these changes

2021-04-09 17:33 UTC, merged